import React from 'react';
import { Route } from 'react-router-dom'

const { Heading, Subhead, Flex, NavLink } = require('rebass') 
const {
    Hero, 
    CallToAction,
    Checklist,
    Contributor,
    ScrollDownIndicator,
    SignUp,
    Section,
    Feature
} = require('react-landing-page')

import Loading from '../Loading/index'

type LandingProps = {

}

const featherCheckmark = <svg
  xmlns="http://www.w3.org/2000/svg"
  width="24" height="24"
  viewBox="0 0 24 24"
  fill="none" stroke="green"
  strokeWidth="2"
  strokeLinecap="round"
  strokeLinejoin="round"
>
  <path d="M22 11.08V12a10 10 0 1 1-5.93-9.14"/>
  <polyline points="22 4 12 14.01 9 11.01"/>
</svg>

export default function Landing () {
    return (
        <Route 
            path="/"
            render={({history}) => (
                <div>
                    <Hero
                        color="black"
                        bg="white"
                        backgroundImage="https://source.unsplash.com/jxaj-UrzQbc/1600x900"
                    >
                        {/* <Loading isLoading={isLoading} /> */}
                        <Heading>Review DAO</Heading>
                        {/* <Subhead>ReviewDAO is a consortium for generating, organizing, and distributing product reviews.</Subhead> */}
                        <CallToAction onClick={() => { history.push('/token-manager') }} mt={3}>Get Started</CallToAction>
                        <ScrollDownIndicator/>
                    </Hero>
                    <Section
                        bg='white'
                        heading="What is ReviewDAO"
                        subhead="ReviewDAO is an open consortium for trading product reviews between indivduals and corporations."
                    >
                        <Feature icon="🔥" description="Massive dataset of the product reviews based upon UPC">
                            Product Reviews
                        </Feature>
                        <Feature icon="🔥" description="Universal dAPP">
                            Features
                        </Feature>
                        <Feature icon="$" description="Users contribute reviews and receive tokens. Those tokens represent ownership rights to a share of the revenue generated by companies purchasing review data streams.">
                            Revenue Sharing
                        </Feature>
                    </Section>
                    <Section 
                        width={1}
                        heading='Why ReviewDAO?'
                        subhead='maybe this will help'>
                        <Checklist children={[
                            'Open Source',
                            'Participant Owned',
                            'Practical API'
                        ]} checkmark={featherCheckmark}/>
                    </Section>
                    {/* <Section
                        bg='white'
                        heading="The Team"
                    >
                        <Contributor
                            fullName="Mike Hathaway"
                            title="Developer"
                            avatar="https://media.licdn.com/dms/image/C4D03AQHrQu7jWlkkmQ/profile-displayphoto-shrink_200_200/0?e=1538006400&v=beta&t=ByDJmdnXciGKEyYXdfj4mA7WNEXCvTWhGfbFm4imqyI"
                            >
                            <Flex>
                                <NavLink href='https://github.com/MikeHathaway'>GitHub</NavLink>
                                <NavLink href='https://www.linkedin.com/in/mike-hathaway'>LinkedIn</NavLink>
                            </Flex>
                        </Contributor>
                    </Section> */}
                    <Section
                        bg='white'
                        heading="Join the Community"
                        subhead="Sign up for the latest content and updates."
                    >
                        {<SignUp onSubmit={(email: any) => alert(`got ${email}`)} mt={3}/>}
                    </Section>
                    <Flex is="footer" alignItems="center" p={3}>
                        <NavLink children="Link 1" href="#"/>
                        <NavLink children="Link 2" href="#"/>
                        {/* <Small color="grey" ml="auto">© Brand, 2018</Small> */}
                    </Flex>
                </div>
        )}/>
    )
}